n1 = int (input('Digite um numero?'))
n2 = int(input('Digite um segundo numero?'))
soma= int(n1 + n2)
#print('A soma dos números é {}'.format(soma))
#print('A soma entre', n1 , 'e', n2, 'vale:', soma)
print('A soma entre {} e {} vale {}'.format(n1, n2, soma))
